name: build_doc

on:
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: docker://pandoc/latex:2.9
        with:
          args: -f markdown -t docx 1/1.服务器协议接口说明.md -o 1/doc/服务器协议接口说明.docx

      - uses: docker://pandoc/latex:2.9
        with:
          args: -f markdown -t docx 1/2.增加新通讯协议说明.md -o 1/doc/增加新通讯协议说明.docx
          
      - uses: docker://pandoc/latex:2.9
        with:
          args: -f markdown -t docx 1/3.服务器代码规范.md -o 1/doc/服务器代码规范.docx

      - uses: docker://pandoc/latex:2.9
        with:
          args: -f markdown -t docx 1/4.服务器库表结构.md -o 1/doc/服务器库表结构.docx

      - name: Commit
        run: |
          git config --global user.email "yaofei365@126.com"
          git config --global user.name "yaofei365"
          git add 1/doc/*.docx
          git commit -am "Automated commit"
          git push
