name: build

on:
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: docker://pandoc/latex:2.9
        with:
          args: -f markdown -t docx 1/1.服务器协议接口说明.md -o 1/1.服务器协议接口说明.docx 
