name: build_doc

on:
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: docker://pandoc/latex:2.9
        with:
          args: -f markdown -t docx 1/1.服务器协议接口说明.md -o 1/1.服务器协议接口说明.docx 

      - name: Commit
        run: |
          git config --global user.email "yaofei365@126.com"
          git config --global user.name "yaofei365"
          git add 1/1.服务器协议接口说明.docx
          git commit -am "Automated commit"
          git push
